name: ecommerce_market_ui
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0        # API cagrilari icin kullanilir
  go_router: ^13.2.2  # routing ozelligi eklemek icin
  url_strategy: ^0.2.0 # routinglerde olusan "#" sembolunu yok etmek icin.
  animated_bottom_navigation_bar: ^1.3.3  # hazir bir animasyonlu BottomNavbar widget paketi
  flutter_riverpod: ^2.4.1 # state management icin : state leri sayfalar arası taşıyabilmek icin..
  web: ^0.5.1  #MacOS => web: ^0.3.0  WinOS => web: ^0.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - /imajlar
  #  - /sesler
  #  - /videolar